spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false
    username: root
    password: 123456

mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml #配置文件所在路径
  type-aliases-package: com.springcloud.entities   #所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/*.xml        #mapper的映射文件
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
#    cache-enabled: true    #开启二级缓存




    dbcp2:
      min-idle: 5          #初始化连接数
      initial-size: 5       #最大连接数
      max-wait-millis: 200  #等待连接获取最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true #访问路径显示IP地址

info:
  app.name: microservicecloud01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud02?useSSL=false
    username: root
    password: 123456

mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml #配置文件所在路径
  type-aliases-package: com.springcloud.entities   #所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/*.xml        #mapper的映射文件
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
#    cache-enabled: true    #开启二级缓存




    dbcp2:
      min-idle: 5          #初始化连接数
      initial-size: 5       #最大连接数
      max-wait-millis: 200  #等待连接获取最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true #访问路径显示IP地址

info:
  app.name: microservicecloud01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

